# Generated by Django 2.2.2 on 2019-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
