# Generated by Django 2.2.4 on 2019-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190629_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='developer',
            field=models.BooleanField(default=False),
        ),
    ]
