# Generated by Django 2.2.3 on 2019-08-04 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('postId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Podaj tytuł', max_length=50, unique=True)),
                ('synopsis', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('C++', 'C++'), ('Graphics', 'Graphics'), ('Text Editor', 'TextEditor'), ('Spreadsheet', 'Spreadsheet'), ('DataBase', 'DataBase'), ('Web Design', 'WebDesign')], max_length=100)),
                ('level', models.CharField(choices=[('Unknown', 'Unknown'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Unknown', max_length=100)),
                ('content', mdeditor.fields.MDTextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Work In Progress', 'Work-In-Progress'), ('Not Approved Yet', 'Not-Approved-Yet'), ('Approved', 'Approved')], default='Not-Approved-Yet', max_length=100)),
                ('numbers_of_entries', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
    ]
