# Generated by Django 2.2.2 on 2019-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190620_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('D', 'Django'), ('P', 'Python'), ('C', 'C++'), ('G', 'Graphics'), ('W', 'Word'), ('E', 'Excel'), ('Db', 'DataBase')], max_length=100),
        ),
    ]
