# Generated by Django 2.2.2 on 2019-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190620_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('C++', 'C++'), ('Graphics', 'Graphics'), ('Word', 'Word'), ('Excel', 'Excel'), ('DataBase', 'DataBase')], max_length=100),
        ),
    ]
