# Generated by Django 2.2.2 on 2019-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190620_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='synopsis',
            field=models.CharField(default='', max_length=200),
        ),
    ]
