# Generated by Django 2.2.2 on 2019-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='synopsis',
            field=models.TextField(default='', max_length=200),
        ),
    ]
