# Generated by Django 2.2.2 on 2019-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190620_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('postId', models.IntegerField()),
            ],
        ),
    ]
