# Generated by Django 2.2.4 on 2019-08-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Queue'),
        ),
    ]
