# Generated by Django 2.2.4 on 2019-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='description',
            field=models.TextField(default='Brak opisu', max_length=500),
        ),
    ]
