# Generated by Django 2.2.2 on 2019-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_fileuploadurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadurl',
            name='fileName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileuploadurl',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
