# Generated by Django 2.2.2 on 2019-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190623_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadurl',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
