# Generated by Django 2.2.4 on 2019-08-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190812_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='queue',
        ),
        migrations.AddField(
            model_name='queue',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post'),
        ),
    ]
