# Generated by Django 2.2.4 on 2019-08-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190812_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='post',
        ),
        migrations.AddField(
            model_name='queue',
            name='post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
