# Generated by Django 2.2.2 on 2019-06-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_fileuploadurl_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadurl',
            name='file',
        ),
        migrations.AddField(
            model_name='fileuploadurl',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
