# Generated by Django 2.2.4 on 2019-08-13 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20190812_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queue',
            new_name='Cycle',
        ),
    ]
