# Generated by Django 2.2.2 on 2019-06-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190623_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadurl',
            name='author',
        ),
    ]
