# Generated by Django 2.2.2 on 2019-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_fileuploadurl_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='', max_length=100),
        ),
    ]
