# Generated by Django 2.2.4 on 2019-08-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190814_2021'),
        ('blog', '0013_email'),
    ]

    operations = [
    ]
