# Generated by Django 2.2.2 on 2019-06-29 11:28

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190624_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='synopsis',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='CommentOfComment',
        ),
    ]
