# Generated by Django 2.2.4 on 2019-08-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
