# Generated by Django 2.2.4 on 2019-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_delete_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_abbr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('C++', 'C++'), ('Graphics', 'Graphics'), ('TextEditor', 'Text Editor'), ('Spreadsheet', 'Spreadsheet'), ('DataBase', 'Data Base'), ('WebDesign', 'Web Design')], max_length=100),
        ),
    ]
