# Generated by Django 2.2.2 on 2019-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numbers_of_entries',
            field=models.IntegerField(default=0),
        ),
    ]
