# Generated by Django 2.2.3 on 2019-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_numbers_of_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('postId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FileUploadUrl',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('C++', 'C++'), ('Graphics', 'Graphics'), ('Text Editor', 'TextEditor'), ('Spreadsheet', 'Spreadsheet'), ('DataBase', 'DataBase'), ('Web Design', 'WebDesign')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Work In Progress', 'Work-In-Progress'), ('Not Approved Yet', 'Not-Approved-Yet'), ('Approved', 'Approved')], default='Not-Approved-Yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='synopsis',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
