# Generated by Django 2.2.3 on 2019-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190708_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Podaj tytuł', max_length=50, unique=True),
        ),
    ]
