# Generated by Django 2.2.4 on 2019-09-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190906_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='post',
            new_name='posts',
        ),
    ]
