# Generated by Django 2.2.4 on 2019-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190907_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cycle_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='in_cycle',
            field=models.BooleanField(default=False),
        ),
    ]
