# Generated by Django 2.2.4 on 2019-09-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190912_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cycle_title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
