# Generated by Django 2.2.3 on 2019-08-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190801_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.TextField(help_text='Możesz tu umieścić którki opis', max_length=500, null=True),
        ),
    ]
