# Generated by Django 2.2.4 on 2019-09-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190912_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cycle_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='in_cycle',
        ),
    ]
